# Generated by Django 4.1.7 on 2023-03-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entrydetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Ega', 'verbose_name_plural': 'Egalar'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-id',), 'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['number_of_comments'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entrys'},
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(default='malikaegammkulov@gmail.com', max_length=254),
        ),
        migrations.DeleteModel(
            name='EntryDetail',
        ),
    ]
